### ISSUE TITLE
Can't start on mac

### ISSUE THREAD

**Issue by AlfieC** [mcjp78/AltLoaderDownloads#5]
Exception in thread "main" java.lang.NullPointerException
    at java.lang.ProcessBuilder.start(ProcessBuilder.java:1012)
    at Util.JVM.startSecondJVM(JVM.java:23)
    at Main.<init>(Main.java:66)
    at Main.main(Main.java:29)

**Comment by Tomygames** [comment]
with the 0.7.1,it still doesn't start up with the latest JDK , 0:106: execution error: Exception in thread "main" java.lang.ArrayIndexOutOfBoundsExceptat net.altdispenser.altloader.AltLoader.main(AltLoader.java:72) (1)
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
